name: process_loop
description: Runs a looping process. Get a stream of stout is obtained from the process.
version: 0.0.2

homepage: https://github.com/3d24rd0/process_loop
documentation: https://github.com/3d24rd0/process_loop

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
