name: Publish to Pub.dev

on:
  release:
    types: [published]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 

      - name: credentialJson
        id: credentialJson
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: ~/.pub-cache/credentials.json
          encodedString: ${{ secrets.credentialJson }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Download pub dependencies
        run: flutter pub publish --dry-run

