name: Publish to Pub.dev

on:
  release:
    types: [published]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta
          
      - name: Download pub dependencies
        run: flutter pub get

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}